# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  uv = {
    pname = "uv";
    version = "0.9.6";
    src = fetchFromGitHub {
      owner = "astral-sh";
      repo = "uv";
      rev = "0.9.6";
      fetchSubmodules = false;
      sha256 = "sha256-pr93GmvFx2DYt8/LzDSlllwpQ6XZuW7eMWNyEGwbUKg=";
    };
  };
}
