# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  click = {
    pname = "click";
    version = "8.1.8";
    src = fetchurl {
      url = "https://pypi.org/packages/source/c/click/click-8.1.8.tar.gz";
      sha256 = "sha256-7VPJ2JkNg8Kifermjk7jN0c/YzDAQKMdQiXJV00WCWo=";
    };
  };
  tutor = {
    pname = "tutor";
    version = "22.0.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/tutor/tutor-22.0.1.tar.gz";
      sha256 = "sha256-EESytQFyCDXtzHhsasTb5hPwICtnn+1JoDhpRv+JP1k=";
    };
  };
  tutor-android = {
    pname = "tutor-android";
    version = "22.0.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/tutor_android/tutor_android-22.0.0.tar.gz";
      sha256 = "sha256-VYrrjAimvn4oSG2qqtpz44PPOmRX/cBuONftQjsf7YU=";
    };
  };
  tutor-cairn = {
    pname = "tutor-cairn";
    version = "22.0.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/tutor_cairn/tutor_cairn-22.0.0.tar.gz";
      sha256 = "sha256-D7cdg/fMSagsGOiecrRx8xn1dHm1XPypQUT5y8SWB0Y=";
    };
  };
  tutor-credentials = {
    pname = "tutor-credentials";
    version = "22.0.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/tutor_credentials/tutor_credentials-22.0.0.tar.gz";
      sha256 = "sha256-jtITJpoM8zv/abF0ho+dYECTF7FEc9LvVgBokB03l2c=";
    };
  };
  tutor-deck = {
    pname = "tutor-deck";
    version = "22.0.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/tutor_deck/tutor_deck-22.0.0.tar.gz";
      sha256 = "sha256-ATgvhoao1VgIbTqsbW1mfhq/aBEut3/r3Traefm/0hI=";
    };
  };
  tutor-discovery = {
    pname = "tutor-discovery";
    version = "22.0.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/tutor_discovery/tutor_discovery-22.0.0.tar.gz";
      sha256 = "sha256-ynLuUi8AjGhMoN2/0Q2Pasirrsk81Vfa3+6jtdj9H/Y=";
    };
  };
  tutor-forum = {
    pname = "tutor-forum";
    version = "22.0.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/tutor_forum/tutor_forum-22.0.0.tar.gz";
      sha256 = "sha256-v5IPaUzhiDnoKf05PjBWIcLX6iEFtom1e1GyCmtLqbg=";
    };
  };
  tutor-indigo = {
    pname = "tutor-indigo";
    version = "22.0.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/tutor_indigo/tutor_indigo-22.0.0.tar.gz";
      sha256 = "sha256-T0sCJ1hG0oFvNltpc14HpjYcOmTka1A3gf/tQqh3Ei4=";
    };
  };
  tutor-jupyter = {
    pname = "tutor-jupyter";
    version = "22.0.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/tutor_jupyter/tutor_jupyter-22.0.0.tar.gz";
      sha256 = "sha256-UeoJwMD1d69/pGfecIs50lQQ6Rs46hPiD36NjADsRSY=";
    };
  };
  tutor-livedeps = {
    pname = "tutor-livedeps";
    version = "22.0.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/tutor_livedeps/tutor_livedeps-22.0.0.tar.gz";
      sha256 = "sha256-OT8a8df+01Ch8Avs6jpkEa9DbZvZmV0fngy/hpBUHao=";
    };
  };
  tutor-mfe = {
    pname = "tutor-mfe";
    version = "22.0.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/tutor_mfe/tutor_mfe-22.0.0.tar.gz";
      sha256 = "sha256-paejRI/oreV5zYlujZsktJGxigWdrEehCtRXKn5wGB0=";
    };
  };
  tutor-minio = {
    pname = "tutor-minio";
    version = "22.0.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/tutor_minio/tutor_minio-22.0.0.tar.gz";
      sha256 = "sha256-lUKTcDqwifoyAwU3IQs6+kNWfZovogTBQ4jFd+qzy0c=";
    };
  };
  tutor-notes = {
    pname = "tutor-notes";
    version = "22.0.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/tutor_notes/tutor_notes-22.0.0.tar.gz";
      sha256 = "sha256-BBhPzedU6zxNseCTp501967qS4QhiLeEC4+8Wv1udgk=";
    };
  };
  tutor-xqueue = {
    pname = "tutor-xqueue";
    version = "22.0.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/tutor_xqueue/tutor_xqueue-22.0.0.tar.gz";
      sha256 = "sha256-mZNRdw4LjGIOioxWZX2yYdm6HOpWCpyH/dtpuDe70iI=";
    };
  };
  uv = {
    pname = "uv";
    version = "0.9.6";
    src = fetchFromGitHub {
      owner = "astral-sh";
      repo = "uv";
      rev = "0.9.6";
      fetchSubmodules = false;
      sha256 = "sha256-pr93GmvFx2DYt8/LzDSlllwpQ6XZuW7eMWNyEGwbUKg=";
    };
  };
}
